USE MI_STAGING
GO

IF EXISTS(select * FROM sys.views where name = 'vwAAOSHWSets')
	DROP VIEW dbo.vwAAOSHWSets
GO

CREATE VIEW dbo.vwAAOSHWSets
AS
SELECT DISTINCT 
	AH.*,
	CASE WHEN ISNULL(CAST(AH.Qty AS INT), '') = '' THEN 0 ELSE CAST(AH.Qty AS INT) END AS Qty_,
	CHECKSUM(ISNULL(P.ProductID, ISNULL(P2.ProductID, P3.ProductID)) + ISNULL(CAST(CAST(CASE WHEN AH.Qty = 0 THEN AH.Price ELSE AH.Price/AH.Qty END AS DECIMAL(19,2)) AS VARCHAR(MAX)), '-1')) AS PID
FROM dbo.MI_AAOSHWSets AH
INNER JOIN dbo.vwAAOSProjects vAP 
ON AH.ProjectID = vAP.ID
LEFT OUTER JOIN dbo.Products P
ON AH.[Description] COLLATE DATABASE_DEFAULT = P.ProductID COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN [dbo].[Products] P2
ON REPLACE(AH.[Description], AH.Finish,'') = P2.ProductID COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN [dbo].[Products] P3
ON AH.[Description] + '-' + AH.Finish = P3.ProductID COLLATE DATABASE_DEFAULT
INNER JOIN dbo.vwProducts vP ON CHECKSUM(ISNULL(P.ProductID, ISNULL(P2.ProductID, P3.ProductID)) + ISNULL(CAST(CAST(CASE WHEN AH.Qty = 0 THEN AH.Price ELSE AH.Price/AH.Qty END AS DECIMAL(19,2)) AS VARCHAR(MAX)), '-1')) = vP.ID
WHERE ISNULL(P.ProductID, ISNULL(P2.ProductID, P3.ProductID)) IS NOT NULL
AND AH.[Description] <> ''
UNION
SELECT DISTINCT 
	AH.*,
	CASE WHEN ISNULL(CAST(AH.Qty AS INT), '') = '' THEN 0 ELSE CAST(AH.Qty AS INT) END AS Qty_,
	CHECKSUM(ISNULL(AH.[Description] COLLATE DATABASE_DEFAULT, '-1') + ISNULL(AH.Finish COLLATE DATABASE_DEFAULT, '-1') + ISNULL(AH.TypeDescription COLLATE DATABASE_DEFAULT, '-1') + ISNULL(AH.Mfr COLLATE DATABASE_DEFAULT, '-1') + ISNULL(PGS.Level2 COLLATE DATABASE_DEFAULT, '-1')  + ISNULL(PGS.Level3 COLLATE DATABASE_DEFAULT, '-1') + ISNULL(CAST(CAST(CASE WHEN AH.Qty = 0 THEN AH.Price ELSE AH.Price/AH.Qty END AS DECIMAL(19,2)) AS VARCHAR(MAX)), '-1')) AS PID
FROM dbo.MI_AAOSHWSets AH
INNER JOIN dbo.vwAAOSProjects vAP 
ON AH.ProjectID = vAP.ID
LEFT OUTER JOIN dbo.Products P
ON AH.[Description] COLLATE DATABASE_DEFAULT = P.ProductID COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN [dbo].[Products] P2
ON REPLACE(AH.[Description], AH.Finish,'') = P2.ProductID COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN [dbo].[Products] P3
ON AH.[Description] + '-' + AH.Finish = P3.ProductID COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN dbo.ProductGroupStructure PGS
ON CASE WHEN ISNULL(AH.Product, '') = '' THEN '' ELSE SUBSTRING(AH.Product, 1, CHARINDEX('-', AH.Product)-1) END = PGS.ProductType COLLATE DATABASE_DEFAULT
INNER JOIN dbo.vwProducts vP ON CHECKSUM(ISNULL(AH.[Description] COLLATE DATABASE_DEFAULT, '-1') + ISNULL(AH.Finish COLLATE DATABASE_DEFAULT, '-1') + ISNULL(AH.TypeDescription COLLATE DATABASE_DEFAULT, '-1') + ISNULL(AH.Mfr COLLATE DATABASE_DEFAULT, '-1') + ISNULL(PGS.Level2 COLLATE DATABASE_DEFAULT, '-1') + ISNULL(CAST(CAST(CASE WHEN AH.Qty = 0 THEN AH.Price ELSE AH.Price/AH.Qty END AS DECIMAL(19,2)) AS VARCHAR(MAX)), '-1')) = vP.ID
WHERE ISNULL(P.ProductID, ISNULL(P2.ProductID, P3.ProductID)) IS NULL
AND AH.[Description] <> ''
GO
